### ISSUE TITLE
Mocking classes under test

### ISSUE THREAD

**Issue by Ashraf4795** [AhmedOmara14/Cocktail_TDD#1]
I saw you are annotating the classes under testing with @Mock which does not make sense for me, this happens in all your test classes.

**Comment by AhmedOmara14** [comment]
I used @mock so as not to delegate instance. Do u mean not required to use @mock?

**Comment by Ashraf4795** [comment]
> I used @mock so as not to delegate instance. Do u mean not required to use @mock?

I mean, the purpose of unit testing is to test a unit of logic in your app, let us say MainViewModel, so you should test this unit only, then, what u should do is faking all the dependencies the VM needs to control there behavior, hence, you can test ur VM with certainity that no other parties are involved out of ur control, 
So u should create real instance of the unit of logic _(viewmodel)_  that is under test, and mocking/faking what ever else to control ther behavior.

**Comment by AhmedOmara14** [comment]
Ok, I already make that. I added in setup of mainViewModelTest real instance of viewModel 

(viewModel = MainViewModel(repository))

But I added @mock by Mistake ok I will remove it

Thanks Ashraf for your comment

**Comment by MahmoudMabrok** [comment]
I think this occurs also for `CocktailRepositoryImplTest`, I was going to raise a PR.

we should remove @mock  from CocktailRepository.

**Comment by AhmedOmara14** [comment]
@MahmoudMabrok Thanks for your review

**Comment by MahmoudMabrok** [comment]
I think you would close issue, right? 
@Ashraf4795
