### ISSUE TITLE
Remove mock of class under test 

### ISSUE THREAD

**Issue by MahmoudMabrok** [AhmedOmara14/Cocktail_TDD#3]
https://github.com/AhmedOmara14/Cocktail_TDD/blob/cb6d46e937146d55f45677bdc7fdb45d0a0e9194/app/src/test/java/com/omaradev/cocktail/presentation/main/viewmodel/MainViewModelTest.kt#L30

**Comment by AhmedOmara14** [comment]
@MahmoudMabrok Solved in [Integration_Test](https://github.com/AhmedOmara14/Cocktail_TDD/tree/Integration_Test)

**Comment by MahmoudMabrok** [comment]
thanks
